<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="HSM" nsURI="http://HSM/1.0" nsPrefix="HSM">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="unique_hsm_sm_names has_source has_target one_comp unique_state_names"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="unique_hsm_sm_names" value="&#xA;&#x9;&#x9;&#x9;StateMachine.allInstances()->forAll(s1,s2 | s1&lt;>s2 implies s1.name&lt;>s2.name)"/>
      <details key="has_source" value="&#xA;&#x9;&#x9;&#x9;Transition.allInstances()->forAll(t | not t.target.oclIsUndefined())"/>
      <details key="has_target" value="&#xA;&#x9;&#x9;&#x9;Transition.allInstances()->forAll(t | not t.source.oclIsUndefined())"/>
      <details key="one_comp" value="&#xA;&#x9;&#x9;&#x9;AbstractState.allInstances()->forAll(c1,c2 | c1.oclIsTypeOf(CompositeState) and c2.oclIsTypeOf(CompositeState) implies c1=c2)"/>
      <details key="unique_state_names" value="&#x9;&#xA;&#x9;&#x9;&#x9;AbstractState.allInstances()->forAll(s1,s2 | s1&lt;>s2 implies s1.name&lt;>s2.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true" eOpposite="#//Transition/stateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//AbstractState" containment="true" eOpposite="#//AbstractState/stateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//StateMachine"
        eOpposite="#//StateMachine/transitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AbstractState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractState" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//StateMachine"
        eOpposite="#//StateMachine/states"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeState" eType="#//CompositeState"
        eOpposite="#//CompositeState/states"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//AbstractState"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegularState" eSuperTypes="#//AbstractState"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeState" eSuperTypes="#//AbstractState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//AbstractState" eOpposite="#//AbstractState/compositeState"/>
  </eClassifiers>
</ecore:EPackage>
